- requirements.txt
- test-requirements.txt
- tests/integration/network-integration.requirements.txt
This allows us to stop depending on ansible-test to manage our python
dependencies.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/366
> Move requirements to top-level

- plugins/modules/eos_l3_interfaces.py
Fixes  #67412 [issue](https://github.com/ansible/ansible/issues/67412)
modules/eos_l3_interfaces.py
> Fixed Documentation error : eos_l3_interfaces missing list item for IP Address

- plugins/module_utils/network/eos/facts/vlans/vlans.py
- tests/integration/targets/eos_vlans/tests/cli/deleted.yaml
- tests/integration/targets/eos_vlans/tests/cli/merged.yaml
- tests/integration/targets/eos_vlans/tests/cli/overridden.yaml
- tests/integration/targets/eos_vlans/tests/cli/replaced.yaml
- tests/integration/targets/eos_vlans/tests/cli/reset_config.yml
Partially fixes https://github.com/ansible-collections/cisco.ios/issues/19
eos_vlans
state = active was not gathered by facts. Fixed it.
> eos: Fix idempotency issue with eos_vlans

- galaxy.yml
We should have caught this via our build-ansible-collections jobs, but
don't. I've started work on updating our jobs to properly test galaxy
imports.
> Fix galaxy.yml to load correct README.md file

- plugins/cliconf/eos.py
- tests/integration/targets/eos_banner/tests/cli/basic-login.yaml
- tests/unit/modules/network/eos/fixtures/eos_banner_show_banner.txt
Depends-on: https://github.com/ansible-collections/arista.eos/pull/42
Fixes #36 
cliconf/eos.py
Empty lines in banner text was causing the issue. Fix added to accept the empty lines.
used playbook to validate the fix:
```
- name: given VLAN attributes with device configuration
become: true
vars:
lines: |
WARNING: This system is for the use of authorized clients only.
Individuals using the computer network system without
authorization, or in excess of their authorization, are
subject to having all their activity on this computer
network system monitored and recorded by system
personnel.  To protect the computer network system from
unauthorized use and to ensure the computer network systems
is functioning properly, …
```
> eos : Accomodates empty lines in banner text

- plugins/module_utils/network/eos/config/l2_interfaces/l2_interfaces.py
- tests/integration/targets/eos_l2_interfaces/tests/cli/replaced.yaml
- tests/unit/modules/network/eos/test_eos_l2_interfaces.py
Fixes #12 
When providing a list of vlans for trunk_allowed_vlans the list can contain vlan id:s represented as integers (much like the native_vlan parameter) however, the module expects a list of strings, this minor fix convert the items to strings before the join
eos_l2_interfaces
```paste below
```
> eos_l2_interfaces: convert items to strings before joing

- tests/integration/targets/eos_smoke/tasks/cli.yaml
- tests/integration/targets/eos_smoke/tasks/main.yaml
This results in local test jobs running with network_cli, causing job
timeouts.
> Fix test tag for eos_smoke

- tox.ini
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/595
Just outputting that a file needs to be changed, with no hint to the
developer as to what needs to be changed is not useful.
> Print out what changes are needed to satisfy linting

- changelogs/fragments/72-add-rtt.yaml
- plugins/module_utils/network/eos/config/l3_interfaces/l3_interfaces.py
- tests/integration/targets/eos_acl_interfaces/tests/common/rtt.yaml
- tests/integration/targets/eos_acl_interfaces/vars/main.yaml
- tests/integration/targets/eos_interfaces/tests/common/rtt.yaml
- tests/integration/targets/eos_l2_interfaces/tests/common/rtt.yaml
- tests/integration/targets/eos_l3_interfaces/tests/common/rtt.yaml
- tests/integration/targets/eos_lacp_interfaces/tests/common/rtt.yaml
- tests/integration/targets/eos_lldp_interfaces/tests/common/rtt.yaml
- tests/integration/targets/eos_vlans/tests/common/rtt.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/594
Round trip testcase is added as part of the integration test suite for the following RMs
- eos_interfaces
- eos_l2_interfaces
- eos_l3_interfaces
- eos_lacp_interfaces
- eos_lldp_interfaces
- eos_vlans
> [eos]: Add round trip testcase to 2.9 resource modules

- test-requirements.txt
Cap mock for py27 only.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/606
> Clean up test-requirements.txt file

- changelogs/fragments/68-fix-sort-l3-int.yaml
- plugins/module_utils/network/eos/config/l3_interfaces/l3_interfaces.py
- tests/integration/targets/eos_l3_interfaces/tests/common/rtt.yaml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/611
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/612
Fixes #67 
eos_l3_interfaces.py
```paste below
```
> [eos_l3_interfaces] Fixes sort issue in presence of secondary ipv4 address

- changelogs/fragments/91-check-diff.yaml
- plugins/modules/eos_config.py
This reverts commit c20a1fc32b83eff2898ad5394accc16b246a765e.
This gains nothing on non-onbox-diff devices
eos_config
> Revert "Allow --diff and --check to coexist on eos_config (#91)"

- changelogs/fragments/96-changemode-terminalerror.yaml
- plugins/terminal/eos.py
- tests/integration/targets/eos_lag_interfaces/tests/cli/merged.yaml
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/115
related to  #95 
Handled the terminal output error **% Cannot change mode; remove all members and try again.**
terminal/eos.py
> lag_interfaces: Handled change mode stdout error

- changelogs/fragments/113-add-mode-to-examples.yaml
- plugins/modules/eos_l2_interfaces.py
Signed-off-by: GomathiselviS <gomathiselvi@gmail.c
The newly included 'mode' key is added to the examples.
Related to #112 
eos_l2_interfaces.py
```paste below
```
> eos_l2_interfaces: Added 'mode' to examples in documetation

- changelogs/fragments/105-switchport-mode-interfaces.yaml
- plugins/module_utils/network/eos/argspec/interfaces/interfaces.py
- plugins/module_utils/network/eos/config/interfaces/interfaces.py
- plugins/module_utils/network/eos/facts/interfaces/interfaces.py
- plugins/modules/eos_interfaces.py
- tests/integration/targets/eos_interfaces/templates/reset.cfg
- tests/integration/targets/eos_interfaces/tests/common/merged.yaml
- tests/integration/targets/eos_interfaces/tests/common/overridden.yaml
- tests/integration/targets/eos_interfaces/tests/common/replaced.yaml
- tests/integration/targets/eos_interfaces/tests/common/rtt.yaml
- tests/integration/targets/eos_interfaces/vars/main.yaml
- tests/unit/modules/network/eos/fixtures/eos_interfaces_config.cfg
- tests/unit/modules/network/eos/test_eos_interfaces.py
Fixes #101 
eos_interfaces
To set the routed mode for an interface:
```
eos_interfaces:
config:
- name: Ethernet2
description: Configured by Ansible
speed: '10'
duplex: full
mode: layer3
state: merged
```
When **deleted ** is used, the default mode (layer 2 - switchport) will be set for an interface.
> Added 'mode' to eos_interfaces to enable/disable routed mode

- changelogs/fragments/120-forcedspeed-interfaces-config.yaml
- plugins/module_utils/network/eos/config/interfaces/interfaces.py
- plugins/module_utils/network/eos/facts/interfaces/interfaces.py
- tests/unit/modules/network/eos/fixtures/eos_interfaces_config.cfg
- tests/unit/modules/network/eos/test_eos_interfaces.py
Fixes : https://github.com/ansible-collections/arista.eos/issues/117
When speed configuration for the interface changes from `x` to `forced x` ,  the value for duplex is also passed to the `add_config` func (after necessary checks).
eos_interfaces
```paste below
```
> eos_interfaces: Fix issue with 'forced' speed configuration.

- changelogs/fragments/101-l3_interfaces_documentation.yaml
- plugins/modules/eos_l3_interfaces.py
Targets #101 
eos_l2_interfaces should be used for preparing the node with L2 configs. This is explicitly mentioned in the eos_l3_interfaces RM documentaion.
eos_l3_interfaces
```paste below
```
> Add documentation to use the l2_interfaces module for L2 configs, in l3_interfaces module.

- changelogs/fragments/127-drop-local-connection-testing.yaml
- tests/integration/targets/eos_facts/tasks/cli.yaml
- tests/integration/targets/eos_facts/tasks/eapi.yaml
- tests/integration/targets/eos_smoke/tasks/cli.yaml
- tests/integration/targets/eos_smoke/tasks/eapi.yaml
We no longer test local connection for integration tests.
> Remove local connection testing for integration jobs

- requirements.txt
Due to how ansible / ansible-base works now, this ends up messing up
ansible devel testing.  For now, remove the ansible dependency here
until we can create a fake ansible, with the right ansible-base
requirments.
> Drop ansible from requirement.txt

- changelogs/fragments/fixes_eos_interfaces_rm_where_interface_in_description_resulted_in_failure.yaml
- plugins/module_utils/network/eos/facts/interfaces/interfaces.py
- plugins/module_utils/network/eos/facts/l2_interfaces/l2_interfaces.py
- tests/integration/targets/eos_interfaces/tests/common/_parsed.cfg
- tests/integration/targets/eos_interfaces/tests/common/merged.yaml
- tests/integration/targets/eos_interfaces/vars/main.yaml
To fix the bug where the description was being parsed incorrectly as Interface in of eos_*_interfaces. Fixes #86 
eos_*_interfaces
```paste below
```
> To fix the bug where description was being parsed incorrectly as Interface in of eos_*_interfaces

- changelogs/fragments/requires-ansible.yaml
- meta/runtime.yml
- plugins/modules/eos_l3_interface.py
- plugins/modules/eos_vrf.py
- tests/sanity/ignore-2.11.txt
This change starts the process of adding support for execution
environments for running sanity / unit tests.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/748
Depends-On: https://github.com/ansible/ansible/pull/73360
> Updates needed to start using execution environments

- changelogs/fragments/single_user_mode.yaml
- plugins/cliconf/eos.py
- plugins/terminal/eos.py
- tests/integration/targets/eos_smoke/tasks/cli.yaml
- tests/integration/targets/eos_smoke/tests/cli/caching.yaml
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/120
Depends-On: https://github.com/ansible-collections/arista.eos/pull/172
Signed-off-by: NilashishC <nilashishchakraborty8@gmail.com>
- Targets ansible-collections/ansible.netcommon#73
- Add support for ansible_single_user_mode option added in network_cli.
- Re-use device_info dictionary for every session.
cliconf/eos.py
terminal/eos.py
> Add support for single_user_mode

- changelogs/fragments/add_virtual_interface.yaml
- plugins/module_utils/network/eos/argspec/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/eos/config/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/eos/facts/l3_interfaces/l3_interfaces.py
- plugins/modules/eos_l3_interfaces.py
- tests/unit/modules/network/eos/fixtures/eos_l3_interfaces_config.cfg
- tests/unit/modules/network/eos/test_eos_l3_interfaces.py
Fixes #148 
l3_interfaces
Added a new key "virtual" for ipv4 address.
> Add virtual address to l3_interfaces fact

- changelogs/fragments/config_module_warning_msg.yaml
- plugins/modules/eos_config.py
*  Currently the warning message for diff is thrown
for every module run.
*  Based on discussion here https://github.com/ansible/network/discussions/48
a better way of logging the message is through verbose
logs but verbose logging has a known issue https://github.com/ansible-collections/ansible.netcommon/issues/224
*  Hence moving the message under `warnings` key within the task
response if `changed=True`
eos_config
```paste below
```
> Move warning message for eos_config module

- galaxy.yml
Zuul build in `ansible.netcommon` (here https://github.com/ansible-collections/ansible.netcommon/pull/227) fails with
```
Starting galaxy collection install process
Process install dependency map
ERROR! Cannot meet dependency requirement 'ansible.netcommon:2.0.0' for collection arista.eos from source 'ansible-netcommon-2.0.1-dev1.tar.gz'. Available versions before last requirement added: 2.0.1-dev1
Requirements from:
base - 'ansible.netcommon:2.0.1-dev1'
openvswitch.openvswitch - 'ansible.netcommon:*'
junipernetworks.junos - 'ansible.netcommon:*'
cisco.iosxr - 'ansible.netcommon:>=2.0.0'
arista.eos - 'ansible.netcommon:2.0.0'
```
Looks like the changes should help
> Fix galaxy.yml

- changelogs/fragments/add_remove_config_integrationtests.yml
- requirements.txt
- tests/integration/targets/eos_bgp_address_family/tests/common/deleted.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/gathered.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/merged.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/overridden.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/replaced.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/rtt.yaml
- tests/integration/targets/eos_bgp_global/tests/common/deleted.yaml
- tests/integration/targets/eos_bgp_global/tests/common/gathered.yaml
- tests/integration/targets/eos_bgp_global/tests/common/merged.yaml
- tests/integration/targets/eos_bgp_global/tests/common/purged.yaml
- tests/integration/targets/eos_bgp_global/tests/common/replaced.yaml
- tests/integration/targets/eos_bgp_global/tests/common/rtt.yaml
Few integration tests were failing because of some left over configs from the previous tests. Added _remove_config, before starting the tests, so that the setup is clean.
```paste below
```
> Clean the setup before starting every integration test

- changelogs/fragments/vlan_id_alpha_configs.yml
- plugins/module_utils/network/eos/facts/vlans/vlans.py
- requirements.txt
- tests/unit/modules/network/eos/fixtures/eos_vlan_config.cfg
- tests/unit/modules/network/eos/test_eos_vlans.py
Fixes #191 
Skipping vlan_to_list func call, for "vlan internal" and "vlan dynamic" configurations.
```paste below
```
> Skip vlan internal and vlan dynamic configs in vlan_facts

- changelogs/fragments/l3_interfaces_normalize_interface_name.yml
- plugins/module_utils/network/eos/config/l3_interfaces/l3_interfaces.py
- tests/unit/modules/network/eos/fixtures/eos_l3_interfaces_config.cfg
- tests/unit/modules/network/eos/test_eos_l3_interfaces.py
Fixes #193 
eos_l3_interfaces
```paste below
```
> eos_l3_interfaces: Normalize interface name in delete operation

- changelogs/fragments/split_eapi_url.yml
- plugins/modules/eos_eapi.py
- tests/unit/modules/network/eos/fixtures/eos_eapi_show_mgmt.json
Fixes: #174
The output always has a space before and after ':'. Since the submitter of the issue has reported otherwise, the split pattern has been made more generic.
The output from the device used for testing:
```URLs                                         
-------------------------------------------- 
Management1 : https://192.168.122.113:443    
Management1 : http://192.168.122.113:80      
Ethernet1   : https://[2001:db8:feed::1]:443 
Ethernet1   : http://[2001:db8:feed::1]:80   
Unix Socket : unix:/var/run/command-api.sock 
```
```paste below
```
> eos_eapi: Modify split pattern while getting the eapi interface and url

- changelogs/fragments/sshkey_cli_change.yaml
- plugins/modules/eos_user.py
- tests/unit/modules/network/eos/test_eos_user.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/885
Fixes #189 
Cli changed from "username <name> sshkey" to "username <name> ssh-key".
```paste below
```
> Support 'username sshkey' cli change in eos 4.23

- changelogs/fragments/fix_password_regex.yaml
- plugins/terminal/eos.py
Regex is modified to accept "password" and "Password".
Fixes #210 
```paste below
```
> Fix regex for password prompt

- changelogs/fragments/add_aliases.yml
- docs/arista.eos.eos_bgp_global_module.rst
- plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
- plugins/modules/eos_bgp_global.py
- tests/unit/modules/network/eos/test_eos_bgp_global.py
Added aliases (neighbors and networks) to neighbor and network, since lists of objects, should be plural.
```paste below
```
> eos_bgp_global: Add aliases to network and neighbor

- changelogs/fragments/support_multiple_key_ip_dict_route_maps.yml
- plugins/module_utils/network/eos/config/route_maps/route_maps.py
- plugins/module_utils/network/eos/facts/route_maps/route_maps.py
- plugins/module_utils/network/eos/rm_templates/route_maps.py
- tests/unit/modules/network/eos/test_eos_route_maps.py
Fixes: #235 
This PR fixes the typo and other bugs related to the formation of "match ip ....." command in eos route maps.
```paste below
```
> eos_route_maps:Add support for multiple keys under match.ip/ipv6 in rmtemplate

- changelogs/fragments/disable_integration_tests.yaml
- tests/integration/targets/eos_bgp_address_family/defaults/main.yaml
- tests/integration/targets/eos_bgp_global/defaults/main.yaml
- tests/integration/targets/eos_lacp_interfaces/defaults/main.yaml
- tests/integration/targets/eos_lldp_global/defaults/main.yaml
- tests/integration/targets/eos_static_routes/defaults/main.yaml
- tests/integration/targets/eos_system/defaults/main.yaml
- tests/integration/targets/eos_vrf/defaults/main.yaml
The tests will be enabled, once failures due to cli changes in the latest sw version of eos, are fixed.
```paste below
```
> Disable intergration tests inorder to support eos image upgrade

- changelogs/fragments/bgp_cli_change.yaml
- plugins/module_utils/network/eos/argspec/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
- plugins/module_utils/network/eos/providers/cli/config/bgp/process.py
- plugins/modules/eos_bgp.py
- plugins/modules/eos_bgp_address_family.py
- plugins/modules/eos_bgp_global.py
- tests/integration/targets/eos_bgp_address_family/defaults/main.yaml
- tests/integration/targets/eos_bgp_address_family/templates/populate.cfg
- tests/integration/targets/eos_bgp_address_family/tests/common/_parsed.cfg
- tests/integration/targets/eos_bgp_address_family/tests/common/_redirection.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/merged.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/overridden.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/rendered.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/replaced.yaml
- tests/integration/targets/eos_bgp_address_family/tests/common/rtt.yaml
- tests/integration/targets/eos_bgp_address_family/vars/main.yaml
- tests/integration/targets/eos_bgp_global/defaults/main.yaml
- tests/integration/targets/eos_config/defaults/main.yaml
- tests/integration/targets/eos_interface/defaults/main.yaml
- tests/integration/targets/eos_ospfv3/defaults/main.yaml
- tests/unit/modules/network/eos/fixtures/eos_bgp_af_config.cfg
- tests/unit/modules/network/eos/test_eos_bgp_address_family.py
When running the integration tests in this repo against a VM with 4.26.1F, the tests fail because of a typo.
```
TASK [eos_bgp_address_family : Replace given bgp_address_family configuration] ***************************************
fatal: [localvm]: FAILED! => {"changed": false, "msg": "value of protocol must be one of: isis, ospf3, dhcp, got: ospfv3 found in config -> address_family -> redistribute"}
```
```
localhost#show version
vEOS
Hardware version:
Serial number:
Hardware MAC address: 000c.29a9.1d52
System MAC address: 000c.29a9.1d52
Software image version: 4.26.1F
Architecture: x86_64
Internal build version: 4.26.1F-22602519.4261F
Internal build ID: 1eca5f74-3ced-441a-9137-c966e8f0319d
Image format version: 01.00
Uptime: 0 weeks, 0 days, 1 hours and 8 minutes
Total memory: 4002556 …
```
> Fix ospf3 to be ospfv3

- changelogs/fragments/bgp_listen_limit_cli_change.yml
- plugins/module_utils/network/eos/rm_templates/bgp_global.py
- tests/integration/targets/eos_bgp_global/tests/common/merged.yaml
- tests/integration/targets/eos_bgp_global/tests/common/rendered.yaml
- tests/integration/targets/eos_bgp_global/tests/common/rtt.yaml
- tests/integration/targets/eos_bgp_global/vars/main.yaml
- tests/unit/modules/network/eos/test_eos_bgp_global.py
Related  #https://github.com/ansible-collections/arista.eos/issues/133
This PR takes care of changing the 'bgp listen limit' cli which is no more supported in eos sw versions >= 4.23.
```paste below
```
> Change 'bgp listen limit' to 'dynamic peer max'

- changelogs/fragments/remove_debug_from_tests.yaml
- tests/integration/targets/eos_eapi/tests/cli/off.yaml
- tests/integration/targets/eos_eapi/tests/cli/on.yaml
- tests/integration/targets/eos_eapi/tests/cli/start.yaml
- tests/integration/targets/eos_eapi/tests/cli/stop.yaml
This avoids the need to setup inventory variables.
> Remove unused debug statements

- changelogs/fragments/bgp_global_access_group_list.yaml
- docs/arista.eos.eos_bgp_global_module.rst
- docs/arista.eos.eos_bgp_module.rst
- docs/arista.eos.eos_eapi_module.rst
- docs/arista.eos.eos_interface_module.rst
- docs/arista.eos.eos_l2_interface_module.rst
- docs/arista.eos.eos_l3_interface_module.rst
- docs/arista.eos.eos_linkagg_module.rst
- docs/arista.eos.eos_logging_module.rst
- docs/arista.eos.eos_static_route_module.rst
- docs/arista.eos.eos_vlan_module.rst
- plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
- plugins/module_utils/network/eos/config/bgp_global/bgp_global.py
- plugins/module_utils/network/eos/rm_templates/bgp_global.py
- plugins/modules/eos_bgp_global.py
- tests/unit/modules/network/eos/test_eos_bgp_global.py
Fixes #281 
```paste below
```
> Enable eos_bgp_global access_group take both IPv4 and IPv6 groups

- changelogs/fragments/280-command-spec.yaml
- docs/arista.eos.eos_command_module.rst
- docs/arista.eos.eos_eapi_module.rst
- meta/runtime.yml
- plugins/modules/eos_command.py
- plugins/modules/eos_logging.py
Is it possible to do this with a doc_fragment instead?
We should also probably rework the documentation of `commands` itself as well
eos_command
> Document expected suboptions to eos_command's commands argument

- changelogs/fragments/skip_unwanted_configs_bgp_af.yaml
- plugins/module_utils/network/eos/facts/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/eos/facts/bgp_global/bgp_global.py
- tests/unit/modules/network/eos/fixtures/eos_bgp_af_config.cfg
- tox.ini
Fixes #308
'show running-config | section bgp' lists all the available bgp configs on the device. The assumption that only configs under "router bgp <>" will be listed is broken. Fixed this by adding logic to skip the other irrelevant configs.
```paste below
```
> Skip irrelevant configs while gathering bgp af facts

- changelogs/fragments/fix_documentation_eos_l2_interfaces.yml
- plugins/modules/eos_l2_interfaces.py
There is an invalid parameter used in example for eos_l2_interfaces
eos_l2_interfaces
There was an error in example which ends up in documentation causing documentation to be incorrect. This PR fixes one such case
> Fix invalid example in eos_l2_interfaces

- changelogs/fragments/fast_sessions.yaml
- plugins/cliconf/eos.py
- plugins/httpapi/eos.py
- plugins/module_utils/network/eos/eos.py
If a task runs quickly enough, the next task may start in the same second. As we generate session names based on `time.time()`, this will mean that the next task will also try to reuse the same session name and fail. This PR raises the precision used for session names to two decimal places to avoid that.
cliconf
httpapi
```paste below
```
> Raise precision of cliconf sessions

- changelogs/fragments/fix_virtual_ip_facts_issue.yaml
- plugins/module_utils/network/eos/facts/l3_interfaces/l3_interfaces.py
- tests/unit/modules/network/eos/test_eos_l3_interfaces.py
resolve: https://github.com/ansible-collections/arista.eos/issues/388
```paste below
```
> Fix secondary ip address parsing

- changelogs/fragments/bugfixes_return_empty_data_structure_for_no_facts.yaml
- plugins/module_utils/network/eos/facts/static_routes/static_routes.py
- plugins/module_utils/network/eos/facts/vlans/vlans.py
- tests/integration/targets/eos_facts/tests/cli/network_facts
- Return empty lists for static_routes or vlans when not configured
Resolves: 
- https://github.com/ansible-collections/arista.eos/issues/517 
- https://github.com/network-automation/toolkit/issues/47
- eos_static_routes 
- eos_valns
```paste below
---
- name: Network Facts
hosts: eos
collections:
- arista.eos
tasks:
- name: Gather arista eos facts
arista.eos.eos_facts:
gather_subset: config
gather_network_resources: "{{ 'all' }}"
Output: 
ospf_interfaces:
- name: Ethernet1
- name: Ethernet2
- name: Management0
- name: Management1
- name: Vlan100
ospfv2: {}
ospfv3: []
prefix_lists: []
snmp_server: {}
static_routes: []
vlans: []
changed: false
failed: false
```
> Return empty lists for static_routes or vlans when not configured

- changelogs/fragments/lag_interface_docupdate.yml
- docs/arista.eos.eos_lag_interfaces_module.rst
- plugins/modules/eos_lag_interfaces.py
Updated the examples for eos_lag_interfaces.
- `eos_lag_interfaces`
The `name` attribute in the examples of eos_lag_interfaces was not updated. This pr was opened because of issue #515. Found that `normalize_interface` function takes in the input and normalizes it. It expects input as a string which contains prefix `po`. The examples only had numbers as value.
> Update examples for lag_interfaces

- tests/integration/targets/eos_lacp_interfaces/tests/common/deleted.yaml
- tests/integration/targets/eos_lacp_interfaces/tests/common/gathered.yaml
- tests/integration/targets/eos_lacp_interfaces/tests/common/merged.yaml
- tests/integration/targets/eos_lacp_interfaces/tests/common/overridden.yaml
- tests/integration/targets/eos_lacp_interfaces/tests/common/replaced.yaml
- tests/integration/targets/eos_lacp_interfaces/tests/common/rtt.yaml
- Fixed an testing issue where lacp interfaces configuration was not properly cleaned up after operations that changed the configuration, 
resulting in config spill over. This update ensures that the configuration is correctly reset,
preventing any unintended spill over.
```paste below
```
> Fix lacp interface configuration cleanup to prevent spill over

- changelogs/fragments/fix_statis_routes_ds_issue.yaml
- plugins/module_utils/network/eos/facts/static_routes/static_routes.py
- tests/integration/targets/eos_static_routes/tests/common/_parsed.cfg
- tests/integration/targets/eos_static_routes/tests/common/parsed.yaml
- Ensure IPv6 static route definitions are correctly filtered during facts gathering.
- Update the filter to accurately retrieve relevant static route configurations.
- Update integration tests for parse operations to ensure that ordering or address family (AF) does not affect assertions.
eos_static_routes
> Fix IPv6 static routes facts

- changelogs/fragments/fix_acls_config_drift.yaml
- plugins/module_utils/network/eos/config/acls/acls.py
- tests/integration/targets/eos_acls/tests/common/deleted.yaml
- tests/integration/targets/eos_acls/tests/common/merged.yaml
- tests/unit/modules/network/eos/test_eos_acls.py
This PR addresses an issue in the `compare_configs` method where redundant `no <sequence_number>` 
commands were being generated for Access Control List (ACL) entries that were already present 
in both the `have` and `want` configurations. The root cause was incomplete validation logic for 
sequence numbers and entry content. The updated implementation ensures that only necessary 
commands are generated, aligning with the intended behavior.
- Enhanced validation logic to accurately compare ACL entries between `have` and `want`.
- Optimized handling of sequence numbers and entry content to avoid generating unnecessary 
configuration changes.
- Prevents redundant configuration commands, reducing configuration drift and improving 
efficiency.
- Ensures the `compare_configs` method accurately …
> Fix ACLs config drift issue

- README.md
- changelogs/fragments/bump216.yaml
- meta/runtime.yml
- tests/config.yml
Bump minimum ansible version to 2.16
> Bump minimum ansible version to 2.16
