ansible-collections/arista.eos

galaxy.yml

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/354

Update galaxy.yml for new repo location

---

plugins/module_utils/network/eos/argspec/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/eos/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/eos/facts/l2_interfaces/l2_interfaces.py
plugins/modules/eos_l2_interfaces.py
tests/integration/targets/eos_l2_interfaces/tests/cli/cleanup.yml
tests/integration/targets/eos_l2_interfaces/tests/cli/merged.yaml
tests/integration/targets/eos_l2_interfaces/tests/cli/replaced.yaml
tests/integration/targets/eos_l2_interfaces/tests/cli/reset_config.yml
tests/unit/modules/network/eos/test_eos_l2_interfaces.py

Signed-off-by: CaptTrews <capttrews@gmail.com>

Updated from network content collector

---

README.md
README.rst

documentation
```paste below
```

updated arista.eos readme file

---

test-requirements.txt

Add test requirement coverage==4.5.4

[eos]: Add test requirement for test coverage

---

plugins/modules/eos_config.py
plugins/modules/eos_eapi.py
plugins/modules/eos_interface.py
plugins/modules/eos_linkagg.py
tox.ini

Enable E501, E203 for flake8

---

plugins/doc_fragments/eos.py

I also threw in the removal while I was in there. Feel free to argue about the date.
See also ansible-collections/cisco.nxos#77
doc_fragments/eos

Woah, we really should not be promoting provider for eAPI.

---

README.md

Minor edits to the readme file to:
- remove example that isn't using FQCN as that is the approach we want users to follow
- add link to the contributor guide 
- remove version from requirements.txt as it's not needed.
- add note about no deprecation warnings for 2.9
documentation
```paste below
```

added contributor link, etc to readme

---

README.md

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/586

Replace master with main branch for docs

---

changelogs/fragments/80-linkagg-name-parameter.yaml
plugins/module_utils/network/eos/config/lag_interfaces/lag_interfaces.py
plugins/module_utils/network/eos/facts/lag_interfaces/lag_interfaces.py
tests/unit/modules/network/eos/fixtures/eos_lag_interfaces_config.cfg
tests/unit/modules/network/eos/test_eos_lag_interfaces.py

Fixes https://github.com/ansible-collections/arista.eos/issues/79

Use regex to handle linkagg name

---

plugins/httpapi/eos.py

Swap `| json` with `output="json"` in httpapi plugin

---

changelogs/fragments/90-add-ut-lag-interfaces.yaml
tests/unit/modules/network/eos/fixtures/eos_lag_interfaces_config.cfg
tests/unit/modules/network/eos/test_eos_lag_interfaces.py

Add unit testcases to eos_lag_interfaces RM
test_eos_lag_interfaces.py

Add unit testcases - eos_lag_interfaces

---

changelogs/fragments/89-add-ut-l3_interfaces.yaml
plugins/module_utils/network/eos/facts/l3_interfaces/l3_interfaces.py
tests/unit/modules/network/eos/fixtures/eos_l3_interfaces_config.cfg
tests/unit/modules/network/eos/test_eos_l3_interfaces.py

Added unit tests to eos_l3_interfaces RM.
test_eos_l3_interfaces.py
```paste below
```

Add unit testcases - eos_l3_interfaces

---

changelogs/fragments/116-acls-overridden-idempotent.yaml
plugins/module_utils/network/eos/config/acls/acls.py
tests/integration/targets/eos_acls/tests/common/overridden.yaml
tests/unit/modules/network/eos/test_eos_acls.py

eos_acls: Fix to maintain idempotent state for overridden operation

---

changelogs/fragments/115-protocol-options-acls.yaml
plugins/module_utils/network/eos/config/acls/acls.py
plugins/module_utils/network/eos/facts/acls/acls.py

Fixes #114 
eos_acls
```paste below
```

eos_acls: Fixed typo and index out of range errors while handling protocol_options

---

changelogs/fragments/106-lldp_global_unittest.yaml
plugins/module_utils/network/eos/facts/lldp_global/lldp_global.py
tests/unit/modules/network/eos/fixtures/eos_lldp_global_config.cfg
tests/unit/modules/network/eos/test_eos_lldp_global.py

Add unit testcases to lldp_global RM
eos_lldp_global
```paste below
```

Add unit testcases - eos_lldp_global

---

changelogs/fragments/119-idempotent-l2-interfaces.yaml
plugins/module_utils/network/eos/config/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/eos/utils/utils.py
tests/unit/modules/network/eos/fixtures/eos_l2_interfaces_config.cfg
tests/unit/modules/network/eos/test_eos_l2_interfaces.py

Fixes: #118 
eos_l2_interfaces
```paste below
```

eos_l2_interfaces : fix idempotent issue when allowed_vlans is set

---

changelogs/fragments/109-eos-ospfv3-resource-module.yaml

eos_ospfv3: modified changelog type

---

changelogs/fragments/123-ospfv3-description.yaml
plugins/modules/eos_ospfv3.py

Change short description for eos_ospfv3

---

README.md
changelogs/CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/105-switchport-mode-interfaces.yaml
changelogs/fragments/106-lldp_global_unittest.yaml
changelogs/fragments/109-eos-ospfv3-resource-module.yaml
changelogs/fragments/113-add-mode-to-examples.yaml
changelogs/fragments/115-protocol-options-acls.yaml
changelogs/fragments/116-acls-overridden-idempotent.yaml
changelogs/fragments/119-idempotent-l2-interfaces.yaml
docs/arista.eos.eos_eapi_module.rst
docs/arista.eos.eos_interfaces_module.rst
docs/arista.eos.eos_l2_interfaces_module.rst
docs/arista.eos.eos_ospfv3_module.rst

Update changelog - Release 1.1.0

---

changelogs/fragments/update_docs_default_values.yaml
docs/arista.eos.eos_acls_module.rst
docs/arista.eos.eos_eapi_module.rst
docs/arista.eos.eos_l3_interfaces_module.rst
docs/arista.eos.eos_ospf_interfaces_module.rst
plugins/module_utils/network/eos/eos.py
plugins/modules/eos_acls.py
plugins/modules/eos_eapi.py
plugins/modules/eos_l3_interfaces.py
plugins/modules/eos_ospf_interfaces.py

Using ansible-base = 2.10.4 results in sanity failures. This patch fixes those failures.
```paste below
```

Update default values in argspec and module docs

---

changelogs/fragments/eos_config_diff_doc_update.yaml
plugins/modules/eos_config.py

Fixes https://github.com/ansible-collections/ansible.netcommon/issues/189
*  Update doc
*  Add warning message for idempotent pre-requisite
eos_config
```paste below
```

Update doc to clarify on input config pattern and add warning message

---

changelogs/fragments/add_ignore_txt.yaml
plugins/module_utils/network/eos/config/bgp_address_family/bgp_address_family.py
plugins/module_utils/network/eos/config/bgp_global/bgp_global.py
plugins/module_utils/network/eos/config/ospf_interfaces/ospf_interfaces.py
plugins/module_utils/network/eos/config/ospfv3/ospfv3.py
plugins/module_utils/network/eos/rm_templates/bgp_global.py
requirements.txt
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.9.txt

Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/221
```paste below
```

Fix test-sanity-docker failures

---

changelogs/fragments/acl_interfaces_parse_issue.yaml
plugins/module_utils/network/eos/facts/acl_interfaces/acl_interfaces.py
requirements.txt
tests/unit/modules/network/eos/fixtures/eos_acl_interfaces_config.cfg

Fixes: #150 
```paste below
```

eos_acl_interfaces: Fix regex to parse the running config correctly

---

README.md
changelogs/fragments/unbloat-rpc.yaml
docs/arista.eos.eos_config_module.rst
docs/arista.eos.eos_l3_interface_module.rst
docs/arista.eos.eos_vrf_module.rst
plugins/cliconf/eos.py

See also https://github.com/ansible-collections/vyos.vyos/pull/122
cliconf

Prevent subsequent calls to get_capabilities from duplicating entries in rpc

---

changelogs/CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/acl_interfaces_parse_issue.yaml
changelogs/fragments/add_ignore_txt.yaml
changelogs/fragments/add_virtual_interface.yaml
changelogs/fragments/change_import_resoure_module.yaml
changelogs/fragments/config_module_warning_msg.yaml
changelogs/fragments/ospf_bfd_command_syntax_4_23.yaml
changelogs/fragments/single_user_mode.yaml
changelogs/fragments/unbloat-rpc.yaml
docs/arista.eos.eos_cliconf.rst
docs/arista.eos.eos_l3_interfaces_module.rst
docs/arista.eos.eos_ospfv2_module.rst
galaxy.yml
requirements.txt

EOS 2.0.0 release doc update

---

changelogs/fragments/177-remove_tests_sanity_requirements.yml
galaxy.yml
tests/sanity/requirements.txt

https://github.com/ansible-collections/overview/issues/43

Remove tests/sanity/requirements.txt

---

changelogs/fragments/123-ospfv3-description.yaml
plugins/modules/eos_vlans.py
requirements.txt

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/771
```paste below
```

Add Libssh requirement

---

.pre-commit-config.yaml
requirements.txt

Update collection_prep version in pre-commit-config

---

changelogs/fragments/197-add_ignore_txt.yml
tests/sanity/ignore-2.12.txt

Please, after merge, add 2.11 to the test matrix (I didn't find it)
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

Add ignore-2.12.txt

---

changelogs/fragments/196-fix-caching-test-failure.yaml
plugins/modules/eos_interfaces.py
tests/integration/targets/eos_smoke/tasks/cli.yaml
tests/integration/targets/eos_smoke/tests/cli/caching.yaml
tests/sanity/ignore-2.12.txt

Use FQCN for ansible_connection in eos_smoke caching test

---

changelogs/fragments/no_log_mask.yaml
galaxy.yml
plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
plugins/module_utils/network/eos/argspec/ospf_interfaces/ospf_interfaces.py
plugins/module_utils/network/eos/argspec/ospfv3/ospfv3.py
plugins/module_utils/network/eos/facts/bgp_global/bgp_global.py
plugins/module_utils/network/eos/facts/ospf_interfaces/ospf_interfaces.py
plugins/module_utils/network/eos/facts/ospfv3/ospfv3.py
plugins/module_utils/network/eos/rm_templates/bgp_global.py
plugins/module_utils/network/eos/rm_templates/ospf_interfaces.py
plugins/modules/eos_user.py
tests/integration/targets/eos_ospfv3/tests/common/rtt.yaml
tests/integration/targets/eos_ospfv3/vars/main.yaml
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt

Fixes #https://github.com/ansible-collections/arista.eos/issues/186
```paste below
```

Mask sensitive key values from module result

---

changelogs/fragments/184_available_network_resources.yaml
plugins/module_utils/network/eos/argspec/facts/facts.py
plugins/modules/eos_facts.py
tests/integration/targets/eos_facts/tests/cli/all_facts.yaml

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
resolve: https://github.com/ansible-collections/arista.eos/issues/184
eos_facts
```paste below
```

EOS: available_network_resources implemented in eos_facts

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/196-fix-caching-test-failure.yaml
changelogs/fragments/197-add_ignore_txt.yml
changelogs/fragments/200-add-eos-route-maps.yaml
changelogs/fragments/l3_interfaces_normalize_interface_name.yml
changelogs/fragments/no_log_mask.yaml
changelogs/fragments/split_eapi_url.yml
changelogs/fragments/vlan_id_alpha_configs.yml
docs/arista.eos.eos_route_maps_module.rst

Prepare eos release 2.1.1

---

changelogs/fragments/fix_typo_bgp_global.yaml
docs/arista.eos.eos_bgp_global_module.rst
docs/arista.eos.eos_facts_module.rst
plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
plugins/module_utils/network/eos/config/bgp_global/bgp_global.py
plugins/module_utils/network/eos/rm_templates/bgp_global.py
plugins/modules/eos_bgp_global.py
tests/unit/modules/network/eos/test_eos_bgp_global.py

Fixes #206 
This PR also takes care of improving the test coverage for eos_bgp_global module.
```paste below
```

eos_bgp_global: Fix typo in argspec key

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/184_available_network_resources.yaml
changelogs/fragments/black.yaml
changelogs/fragments/changelog_doc_path_update.yaml
changelogs/fragments/fix_password_regex.yaml
changelogs/fragments/fix_typo_bgp_global.yaml
changelogs/fragments/sshkey_cli_change.yaml
docs/arista.eos.eos_bgp_global_module.rst

Prepare eos release 2.1.2

---

CHANGELOG.rst
changelogs/changelog.yaml

Edit changelog for release 2.1.2

---

README.md
changelogs/fragments/update_readme.yml

https://github.com/ansible-community/community-topics/issues/19
- 
README.md

Update README: freenode -> libera.chat

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/add-eos-prefix-lists.yaml
changelogs/fragments/add_aliases.yml
changelogs/fragments/fix_redirection_typo.yml
changelogs/fragments/update_readme.yml
docs/arista.eos.eos_prefix_lists_module.rst

Prepare eos release 2.2.0

---

changelogs/fragments/230_empty_config_facts.yml
plugins/module_utils/network/eos/config/ospf_interfaces/ospf_interfaces.py
plugins/module_utils/network/eos/config/prefix_lists/prefix_lists.py
plugins/module_utils/network/eos/config/route_maps/route_maps.py
tests/integration/targets/eos_ospf_interfaces/tests/common/gathered_empty_config.yml
tests/integration/targets/eos_prefix_lists/tests/common/deleted.yaml
tests/integration/targets/eos_route_maps/tests/common/deleted.yaml

Fixes #229 
```paste below
```

Empty config should return a list for a module with config of type list

---

changelogs/fragments/set_allow_duplicates.yaml
tests/integration/targets/prepare_eos_tests/meta/main.yaml

Add allow_duplicates to prepare_eos_tests role

---

changelogs/fragments/template_to_support_jinja2.10.3.yaml
plugins/module_utils/network/eos/rm_templates/route_maps.py

Fix command template to support Jinja version in EE

---

changelogs/fragments/cleanup_tags_for_tests.yaml
tests/integration/targets/eos_bgp_address_family/tasks/main.yaml
tests/integration/targets/eos_config/tasks/main.yaml
tests/integration/targets/eos_facts/tasks/cli.yaml
tests/integration/targets/eos_facts/tasks/eapi.yaml
tests/integration/targets/eos_facts/tasks/main.yaml
tests/integration/targets/eos_smoke/tasks/cli.yaml
tests/integration/targets/eos_smoke/tasks/main.yaml
tests/integration/targets/prepare_eos_tests/tasks/main.yml

A few fixes to reduce duplicate testing.

Clean up integration test tags

---

changelogs/fragments/bgp_global_typo_fix.yaml
plugins/module_utils/network/eos/facts/bgp_global/bgp_global.py
plugins/module_utils/network/eos/rm_templates/bgp_global.py
tests/unit/modules/network/eos/fixtures/eos_bgp_global_config.cfg
tests/unit/modules/network/eos/test_eos_bgp_global.py

Fixes #273 
```paste below
```

Fix typo and logic errors in bgp_global

---

.pre-commit-config.yaml
docs/arista.eos.eos_bgp_module.rst
docs/arista.eos.eos_eapi_module.rst
docs/arista.eos.eos_interface_module.rst
docs/arista.eos.eos_l2_interface_module.rst
docs/arista.eos.eos_l3_interface_module.rst
docs/arista.eos.eos_linkagg_module.rst
docs/arista.eos.eos_logging_module.rst
docs/arista.eos.eos_static_route_module.rst
docs/arista.eos.eos_vlan_module.rst

Committed via https://github.com/asottile/all-repos

Updating collection_prep pre-commit hook to 0.9.4

---

changelogs/fragments/deprecation_biannually.yaml
meta/runtime.yml
plugins/modules/eos_bgp.py
plugins/modules/eos_logging.py

Deprecation of modules/argspec keys will be done either in January or July of the specified deprecation year.
```paste below
```

Deprecations will be done biannually (Jan and July).

---

changelogs/fragments/bgp_global_neighbor_replaced.yaml
plugins/module_utils/network/eos/config/bgp_global/bgp_global.py
tests/unit/modules/network/eos/test_eos_bgp_global.py

Fixes #265 
```paste below
```

Fix keyerror while executing eos_bgp_global replaced operation

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/bgp_global_access_group_list.yaml
changelogs/fragments/bgp_global_neighbor_replaced.yaml
changelogs/fragments/bgp_global_typo_fix.yaml
changelogs/fragments/cleanup_tags_for_tests.yaml
changelogs/fragments/deprecation_biannually.yaml
changelogs/fragments/eos_ntp_global_module.yaml
changelogs/fragments/remove_debug_from_tests.yaml
changelogs/fragments/remove_provider_from_tests.yaml
changelogs/fragments/set_allow_duplicates.yaml
changelogs/fragments/template_to_support_jinja2.10.3.yaml
docs/arista.eos.eos_ntp_global_module.rst

Prepare eos release 3.1.0

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/0-copy_ignore_txt.yml
changelogs/fragments/280-command-spec.yaml
changelogs/fragments/eos_snmp_server.yaml
changelogs/fragments/remove_2.6_ignores.yml
changelogs/fragments/support_version_parameter.yaml
docs/arista.eos.eos_facts_module.rst
docs/arista.eos.eos_snmp_server_module.rst

Prepare eos release 4.0.0

---

changelogs/fragments/295-eos-acls-examples-fix.yaml
docs/arista.eos.eos_acls_module.rst
plugins/modules/eos_acls.py

Fix errors in Arista ACLs readme found after testing.
arista.eos.eos_acls
```paste below
```

Fix eos_acls documentation errors

---

changelogs/fragments/297-eos-acl-fix-replaced.yaml
plugins/module_utils/network/eos/config/acls/acls.py
tests/unit/modules/network/eos/test_eos_acls.py

FIxes #296
arista.eos.eos_acls
Refer to #296 for the same example
```paste below
"commands": [
"ip access-list test1",
"no 10",
"no 20",
"no 30",
"3 permit tcp 3.0.0.0/8 any"
],
"commands": [
"ip access-list test1",
"no 10",
"no 20",
"no 30",
"1 permit tcp 1.0.0.0/8 any",
"2 permit tcp 2.0.0.0/8 any",
"3 permit tcp 3.0.0.0/8 any"
],
```

Fix arista.eos.eos_acls replaced state for new ACEs

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/295-eos-acls-examples-fix.yaml
changelogs/fragments/297-eos-acl-fix-replaced.yaml
changelogs/fragments/add_eos_hostname.yaml
test-requirements.txt

EOS release 4.1.0

---

changelogs/fragments/bgp_check_mode_support.yml
plugins/modules/eos_bgp_address_family.py
plugins/modules/eos_bgp_global.py

Fixes #310 
```paste below
```

Add check mode support to bgp_global and bgp_address_family

---

meta/runtime.yml
plugins/modules/eos_command.py

Workaround fix to #311 
Issue submitted under ansible/ansible : https://github.com/ansible/ansible/issues/77059
```paste below
```

Fix redirect to use an action plugin with matching prefix

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/bgp_check_mode_support.yml
changelogs/fragments/fix_documentation_eos_l2_interfaces.yml
changelogs/fragments/skip_unwanted_configs_bgp_af.yaml
docs/arista.eos.eos_l2_interfaces_module.rst

Prepare eos 4.1.1 for release

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/add_alias_bgp_global_peer.yaml
changelogs/fragments/add_symlink_redirection.yml

Prepare eos release 4.1.2

---

changelogs/fragments/fix_snmp_server_communities.yaml
plugins/module_utils/network/eos/rm_templates/snmp_server.py
tests/unit/modules/network/eos/test_eos_snmp_server.py

Fixes #334 
```paste below
```

eos_snmp_server: Fix to change communities without an ACL attached

---

changelogs/fragments/eos_facts_update.yaml
docs/arista.eos.eos_facts_module.rst
plugins/module_utils/network/eos/argspec/facts/facts.py
plugins/modules/eos_facts.py
tests/integration/targets/eos_facts/tests/cli/default_facts.yaml
tests/integration/targets/eos_facts/tests/eapi/default_facts.yaml

fixes #306 
```paste below
```

eos_facts: change default subset to min

---

changelogs/fragments/add_bgp_global_neighor_bfd.yaml
docs/arista.eos.eos_bgp_global_module.rst
plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
plugins/module_utils/network/eos/config/bgp_global/bgp_global.py
plugins/module_utils/network/eos/rm_templates/bgp_global.py
plugins/modules/eos_bgp_global.py
tests/unit/modules/network/eos/test_eos_bgp_global.py

Fixes #339 
```paste below
```

Add bgp_global neighbor bfd parser and fix send-community parser

---

changelogs/fragments/fix_bgp_global_ecmp_render.yaml
plugins/module_utils/network/eos/rm_templates/bgp_global.py
test-requirements.txt
tests/unit/modules/network/eos/test_eos_bgp_global.py

Fixes one of the issues in #339 
```paste below
```

Fix parser for bgp maximum-paths

---

CHANGELOG.rst
README.md
changelogs/changelog.yaml
changelogs/fragments/0-ignore.yml
changelogs/fragments/346-httpapi.yaml
changelogs/fragments/add_bgp_global_neighor_bfd.yaml
changelogs/fragments/eos_facts_remove_warning.yaml
changelogs/fragments/eos_facts_update.yaml
changelogs/fragments/fix_bgp_global_ecmp_render.yaml
changelogs/fragments/fix_eos_acls_protocol_options.yml
changelogs/fragments/fix_snmp_server_communities.yaml
changelogs/fragments/netcommon_ref_update.yaml

Eos release 5.0.0

---

changelogs/fragments/fix_acls_replaced.yaml
plugins/module_utils/network/eos/config/acls/acls.py
tests/unit/modules/network/eos/test_eos_acls.py

Fixes #353 
```paste below
```

Fix eos_acls to add new aces using replaced and overridden state

---

changelogs/fragments/normalize_ntp_server_source.yaml
plugins/module_utils/network/eos/config/ntp_global/ntp_global.py
plugins/module_utils/network/eos/rm_templates/ntp_global.py
tests/unit/modules/network/eos/test_eos_ntp_global.py

Fix #361 
eos_ntp_global.py
```paste below
```

Noramlize ntp server source interface name

---

changelogs/fragments/l3_interfaces_overridden_new_int.yaml
plugins/module_utils/network/eos/config/l3_interfaces/l3_interfaces.py
tests/unit/modules/network/eos/test_eos_l3_interfaces.py

Fixes #360 
Fixes #362 
eos_l3_interfaces.py
```paste below
```

Fix eos_l3_interfaces overriden operation

---

.pre-commit-config.yaml
changelogs/fragments/pre-commit.yaml

Update collection-prep version in pre-commit

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/fast_sessions.yaml
changelogs/fragments/fix_acls_replaced.yaml
changelogs/fragments/l3_interfaces_overridden_new_int.yaml
changelogs/fragments/normalize_ntp_server_source.yaml
changelogs/fragments/pre-commit.yaml

Eos Release 5.0.1

---

changelogs/fragments/diff_against_validate_config.yaml
plugins/cliconf/eos.py
plugins/module_utils/network/eos/eos.py
plugins/modules/eos_config.py
tests/integration/targets/eos_config/tests/cli/diff_against_config.yaml

Fixes #348 
```paste below
```

Add diff_against: validate_config in eos_config

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/bgp_global_neighbor_password.yml
changelogs/fragments/diff_against_validate_config.yaml
changelogs/fragments/github_actions.yaml
changelogs/fragments/net_remove.yaml
changelogs/fragments/remove_deprecated_modules.yaml
changelogs/fragments/remove_provider.yaml
changelogs/fragments/sanity.yaml

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
```paste below
```

Prepare Release 6.0.0

---

.isort.cfg
changelogs/fragments/rm_base.yaml
plugins/module_utils/network/eos/argspec/ospfv2/ospfv2.py
plugins/module_utils/network/eos/config/bgp_address_family/bgp_address_family.py
plugins/module_utils/network/eos/config/bgp_global/bgp_global.py
plugins/module_utils/network/eos/config/logging_global/logging_global.py
plugins/module_utils/network/eos/config/ntp_global/ntp_global.py
plugins/module_utils/network/eos/config/ospf_interfaces/ospf_interfaces.py
plugins/module_utils/network/eos/config/ospfv2/ospfv2.py
plugins/module_utils/network/eos/config/ospfv3/ospfv3.py
plugins/module_utils/network/eos/config/prefix_lists/prefix_lists.py
plugins/module_utils/network/eos/config/route_maps/route_maps.py
plugins/module_utils/network/eos/rm_templates/bgp_address_family.py
plugins/module_utils/network/eos/rm_templates/bgp_global.py
plugins/module_utils/network/eos/rm_templates/logging_global.py
plugins/module_utils/network/eos/rm_templates/ntp_global.py
plugins/module_utils/network/eos/rm_templates/ospf_interfaces.py
plugins/module_utils/network/eos/rm_templates/ospfv3.py
plugins/module_utils/network/eos/rm_templates/prefix_lists.py
plugins/module_utils/network/eos/rm_templates/route_maps.py
tests/unit/modules/network/eos/test_eos_route_maps.py

The old name will be removed in netcommon 5.0.0

Redirect ResourceModule to new location

---

changelogs/fragments/fix_ntp_global_authenticate.yaml
plugins/module_utils/network/eos/rm_templates/ntp_global.py
plugins/modules/eos_config.py
tests/unit/modules/network/eos/test_eos_ntp_global.py

Signed-off-by: rohitthakur2590 <rohitthakur2590@outlook.com>
Fixes: https://github.com/ansible-collections/arista.eos/issues/399
```paste below
```

Fix ntp_global authenticate config

---

changelogs/fragments/trivial_changes.yaml
galaxy.yml
tests/sanity/ignore-2.16.txt

Fix Eos Workflow

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/fix_linting_failures.yaml
changelogs/fragments/fix_ntp_global_authenticate.yaml
changelogs/fragments/rm_base.yaml
changelogs/fragments/sanity_fixes.yaml
changelogs/fragments/trivial_changes.yaml

Prepare release 6.0.1

---

changelogs/fragments/boolean_normalization.yaml
docs/arista.eos.eos_bgp_module.rst
docs/arista.eos.eos_config_module.rst
docs/arista.eos.eos_eapi_module.rst
docs/arista.eos.eos_logging_global_module.rst
docs/arista.eos.eos_ntp_global_module.rst
docs/arista.eos.eos_route_maps_module.rst
docs/arista.eos.eos_user_module.rst
docs/arista.eos.eos_vrf_module.rst
plugins/modules/eos_bgp.py
plugins/modules/eos_config.py
plugins/modules/eos_eapi.py
plugins/modules/eos_logging_global.py
plugins/modules/eos_ntp_global.py
plugins/modules/eos_route_maps.py
plugins/modules/eos_user.py
plugins/modules/eos_vrf.py

Update Docs with boolean normalization

---

changelogs/fragments/no-provider.yaml
tests/integration/targets/eos_smoke/tasks/cli.yaml

This is an artifact of provider and as such is no longer necessary.

Drop `connection: "{{ cli }}"` from eos_smoke test

---

changelogs/config.yaml
changelogs/fragments/update_docs.yaml
docs/arista.eos.eos_bgp_address_family_module.rst
docs/arista.eos.eos_bgp_global_module.rst
docs/arista.eos.eos_ospfv2_module.rst
plugins/module_utils/network/eos/argspec/bgp_global/bgp_global.py
plugins/modules/eos_bgp_address_family.py
plugins/modules/eos_bgp_global.py
plugins/modules/eos_ospfv2.py
tests/integration/targets/eos_bgp_global/tests/common/overridden.yaml
tests/unit/mock/loader.py

Add overridden support and Update Docs 

---

changelogs/fragments/update_ospf_intefaces_docs.yaml
docs/arista.eos.eos_ospf_interfaces_module.rst
plugins/modules/eos_ospf_interfaces.py

Update OSPF interfaces examples

---

changelogs/fragments/ospfv3_docs.yaml
docs/arista.eos.eos_ospfv3_module.rst
plugins/modules/eos_ospfv3.py

Update OSPFv3 examples in docs

---

changelogs/fragments/fix_27_sanity.yaml
plugins/module_utils/network/eos/rm_templates/bgp_address_family.py
plugins/module_utils/network/eos/rm_templates/bgp_global.py
plugins/module_utils/network/eos/rm_templates/ospf_interfaces.py
plugins/module_utils/network/eos/rm_templates/ospfv3.py

Fix python2.7 compile sanity erros

---

changelogs/fragments/conpile_test36.yaml
tests/config.yml

Skip Compile Testing for python 2.x

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/conpile_test36.yaml

Prepare release 6.1.2

---

changelogs/fragments/sanity_job_fix.yaml
tests/sanity/ignore-2.17.txt

Fix sanity job failures

---

changelogs/fragments/ipv6_acl_facts_gather_fix.yaml
plugins/module_utils/network/eos/facts/acls/acls.py
tests/integration/targets/eos_acls/tests/common/_parsed.cfg
tests/integration/targets/eos_acls/tests/common/_parsed_cfg.yaml

resolves: https://github.com/ansible-collections/arista.eos/issues/458
```paste below
```

Fix IPv6 ACE `line` facts generation 

---

changelogs/fragments/docs_fix.yaml
docs/arista.eos.eos_prefix_lists_module.rst
docs/arista.eos.eos_static_routes_module.rst
plugins/modules/eos_prefix_lists.py
plugins/modules/eos_static_routes.py

Fix docs for static routes and prefix lists RMS

---

changelogs/fragments/fix_logging_global_replaced.yaml
plugins/module_utils/network/eos/rm_templates/logging_global.py
tests/unit/modules/network/eos/test_eos_logging_global.py

resolve: https://github.com/ansible-collections/arista.eos/issues/407
```paste below
```

Fix global source_interface config

---

changelogs/fragments/Fix_config.yaml
plugins/modules/eos_config.py
tests/integration/targets/eos_config/templates/basic/interface_config.j2
tests/integration/targets/eos_config/tests/cli/replace_block.yaml
tests/unit/modules/network/eos/test_eos_config.py

Add changes for config module enhancement

---

changelogs/fragments/fix_tox.yaml
tests/unit/modules/network/eos/test_eos_config.py

Fix redefinition lint issue

---

changelogs/fragments/eos_interface_l2_l3.yaml
docs/arista.eos.eos_interfaces_module.rst
docs/arista.eos.eos_l2_interfaces_module.rst
docs/arista.eos.eos_l3_interfaces_module.rst
plugins/modules/eos_interfaces.py
plugins/modules/eos_l2_interfaces.py
plugins/modules/eos_l3_interfaces.py

- "eos_interfaces - update examples and use YAML output for better readability."
- "eos_l2_interfaces - update examples and use YAML output for better readability."
- "eos_l3_interfaces - update examples and use YAML output for better readability."
interface/ l2_interfaces/ l3_interfaces
```paste below
```

[interfaces/l2/l3] eos documentation update

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/Fix_config.yaml
changelogs/fragments/docs_fix.yaml
changelogs/fragments/eos_interface_l2_l3.yaml
changelogs/fragments/fix_logging_global_replaced.yaml
changelogs/fragments/fix_tox.yaml
changelogs/fragments/fix_virtual_ip_facts_issue.yaml
changelogs/fragments/ipv6_acl_facts_gather_fix.yaml
changelogs/fragments/lint_fixtures.yaml
changelogs/fragments/ntp_global_local_interface_fix.yaml
changelogs/fragments/sanity_job_fix.yaml
changelogs/fragments/trivial_lint.yaml

Prepare release 6.2.0

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/ospf_v2_reference_bandwidth_fix.yaml
galaxy.yml

Prepare release 6.2.2

---

changelogs/fragments/fix_downstream_tests.yaml
tests/integration/targets/eos_config/tests/cli/config.yaml

 Update integration tests to avoid hostname conflicts

---

.github/workflows/lint.yml
.github/workflows/tests.yml
CHANGELOG.rst
README.md
changelogs/changelog.yaml
changelogs/fragments/fix_downstream_tests.yaml
docs/arista.eos.eos_lag_interfaces_module.rst
docs/arista.eos.eos_logging_module.rst
galaxy.yml
meta/runtime.yml
plugins/modules/eos_lag_interfaces.py
plugins/modules/eos_logging.py
tests/config.yml

[Major] Prepare release 7.0.0

---

changelogs/fragments/tests_trivial.yaml
tests/integration/targets/eos_config/tests/cli/toplevel.yaml
tests/integration/targets/eos_config/tests/cli/toplevel_after.yaml
tests/integration/targets/eos_config/tests/cli/toplevel_before.yaml

Fix Downstream Integration issues

---

changelogs/fragments/trivial_tests.yaml
tests/integration/targets/eos_user/tests/cli/auth.yaml

Downstream tests fixes

---

test-requirements.txt

update test requirements

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/remove_deprecated.yaml
changelogs/fragments/trivial_tests_updates.yaml
galaxy.yml

Prepare Major Release 8.0.0

---

CHANGELOG.rst
changelogs/changelog.yaml

trivial changes

---

changelogs/fragments/add_restore_support.yaml
galaxy.yml
plugins/cliconf/eos.py

Add support for cli_restore functionality provided with in netcommon

---

CHANGELOG.rst
changelogs/changelog.yaml
changelogs/fragments/218sanity.yml
changelogs/fragments/add_restore_support.yaml

Prepare release 9.0.0

---

tests/integration/targets/eos_lacp_interfaces/tests/common/_remove_config.yaml

trivial:
Add lldp_global config cleanup tasks
```paste below
```

Add LACP Interfaces config cleanup tasks

---

changelogs/fragments/lldp_timer_bugfixes.yaml
plugins/module_utils/network/eos/facts/lldp_global/lldp_global.py

Fix lldp global facts issue

---

docs/arista.eos.eos_bgp_address_family_module.rst
plugins/modules/eos_bgp_address_family.py

Fixes the sanity error
`eos_bgp_address_family`
```paste below
https://github.com/ansible-collections/arista.eos/actions/runs/10189448384/job/28187518883#step:6:318
```

fix sanity error

---

changelogs/fragments/ignore_219.yaml
tests/sanity/ignore-2.19.txt

Fixes the upstream failing nightlies sanity error.
ignore-2.19.txt
```paste below
https://github.com/ansible-collections/arista.eos/actions/runs/11023786153/job/30615752834#step:6:61
```

Adds ignore-2.19.txt

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/fragments/add_vrf_global.yaml
changelogs/fragments/fix_acls_config_drift.yaml
changelogs/fragments/fix_eos_bgp_global.yaml
galaxy.yml

Release Prep 10.1.1

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/fragments/bump216.yaml
galaxy.yml

release PR 11.0.0

---

changelogs/fragments/data_tag.yml
tests/unit/modules/utils.py

Fix data tag related tests

---

changelogs/fragments/route_maps_ipv6.yaml
plugins/module_utils/network/eos/rm_templates/route_maps.py
tests/unit/modules/network/eos/test_eos_route_maps.py

correctly handle ipv6 next-hop
route_maps, set ipv6 next-hop
fixes #570

Update route_maps.py to correctly handle ipv6 next-hop

---

CHANGELOG.rst
changelogs/.plugin-cache.yaml
changelogs/changelog.yaml
changelogs/fragments/data_tag.yml
changelogs/fragments/fix_acls_replace_idemp.yaml
changelogs/fragments/fix_route_map_community.yaml
changelogs/fragments/fix_route_maps_metric.yaml
changelogs/fragments/fix_sanity.yaml
changelogs/fragments/logging_global.yml
changelogs/fragments/route_maps_ipv6.yaml
galaxy.yml

Prep release v11.0.1

---

changelogs/fragments/eos_interfaces.yaml
docs/arista.eos.eos_interfaces_module.rst
plugins/module_utils/network/eos/argspec/interfaces/interfaces.py
plugins/module_utils/network/eos/config/interfaces/interfaces.py
plugins/modules/eos_interfaces.py
tests/integration/targets/eos_interfaces/tests/common/merged.yaml
tests/unit/modules/network/eos/fixtures/eos_interfaces_config.cfg
tests/unit/modules/network/eos/test_eos_interfaces.py

Modify `enabled` behavior on eos_interfaces `merged`
